name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: [6.10.3]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB v${{ matrix.mongodb-version }}
          uses: supercharge/mongodb-github-action@1.2.0
          with:
            mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test 
